### PR TITLE
Added ExitState interface as per our discussion at Hackengarden Zurich

### PR DESCRIPTION
**Pull request by McDime**
Hi @aalmiray,
Added ExitState interface as per our discussion at Hackengarden Zurich on 2 Dec. 2015.

### CODE REVIEW

**Comment by aalmiray** [comment]
please update license headers by running `gradle licenseFormat`. Also, don't forget to add your name in the `@author` tag ;-)

**Comment by McDime** [comment]
Gradle licenseFormat is happy with the already submitted header.
And there are no @author tags in other classes, so I think it is not fare
to use it for this class. Plus I would had to add 4 authors there :)

**Comment by aalmiray** [comment]
Right, sorry I got confused by another project that uses different file headers. The ones included in this PR are correct.

**Comment by keilw** [comment]
Since this is even an API artifact (in the API/Spec repo to my knowledge for JSRs only EG members should make significant, visible contributions) did you ask @McDime to sign the Contributor Agreement?

**Comment by aalmiray** [comment]
No, he didn't sign the JSPA. Contributions made by non EC members are governed under the ASL2. Remember that I had setup an automatic CLA verification using clahub a few months ago? Problem was that all EC members would have to agree on that one too even if their contributions are governed by the JSPA. clahub does not have a feature that can exclude a group from signing a CLA. Anyway, I was sure to let @McDime know that his contributions were governed by ASL2 before the push was sent.

**Comment by keilw** [comment]
EG ;-) The Github main page mentions some "Contributor Agreement", not the JSPA/JCP membership. Until JSR 364 and its new roles like "Contributor" (non EG members that the Spec Lead may even list on the JSR page if their efforts are significant enough and they want to be mentioned) are final, this is still somewhat uncharted territory, especially in core artifacts like API and/or Spec. I am fairly Open Source savvy and friendly myself, but not everyone in the EC, including many at Oracle shares those views...

**Comment by keilw** [comment]
Looking at one of the most open and "unconventional" JSRs (they even publish the Spec under ASL2, but certainly Oracle's and Red Hat's legal teams must have negotiated that somehow;-) CDI, there are very few committers https://github.com/cdi-spec/cdi/graphs/contributors not either Red Hat staff or members of the EG. 1 or 2 maybe.

**Comment by aalmiray** [comment]
argh, I keep typing EC when I mean EG :stuck_out_tongue_winking_eye: 

Correct, CDI allows contributions form non-EG members under ASL2. My goal is for this JSR to function in thew same way. The dead link to the CLA points to clahub. It's a dead link because the CLA was removed due to the forced agreement to ASL2 by EG members even though they have signed the JSPA already.

Personally I have no problem if EG members have to sign a CLA for ASL2. In this way every contribution to this repo would be guaranteed to be machine checked under a CLA. What do you think?

**Comment by keilw** [comment]
I don't think EG members would have to sign a CLA, but non-EG members who contribute probably could/should. I am not sure about those 2/3 people in CDI, Antoine should know, maybe ask him. There could be worries in the EC about IP-flow, I know that's an important topic to them. Red Hat similar to Apache or Eclipse have dedicated IP lawyers for that kind of stuff, I am not sure, if either you or Canoo do if it was necessary? ;-)

**Comment by aalmiray** [comment]
I understand why EG members should not have to sign yet another CLA. If we don't use an automated solution such as clahub for non EG members then we must rely on paperwork (external to the JCP and JSPA because this CLA should be under ASL2), which is tiresome IMHO. Unfortunately clahub is an all or nothing approach, and there are no other integrated options at the moment.

Hence why I thought it may be a good compromise to have every contributor to the JSR377 repos use clahub to assert they have agreed to a CLA. Any dissenting opinions are enough to stop this idea and have us reconsider how to proceed :smile:

**Comment by keilw** [comment]
If it's automated via a site like CLAHub, why not, I guess everyone who took the trouble to sign the (stronger) JSPA already should be OK with it ;-)

**Comment by aalmiray** [comment]
OK, I'll re instantiate the CLA via clahub to have everybody be on the same page :smiley_cat:

**Pull request merged**
